### PR TITLE
Check for existing expression

### PR DESCRIPTION
**Pull request by henrikmw**
And sort suggestions by id, nice to have when people say they sent a suggestion to be able to quickly identify it

### CODE REVIEW

**Review by MarkusJohansen — CHANGES_REQUESTED** [review]
This verifies if the expression exists in the database, but only exactly.

Imagine that the expression "En vinge" is in the DB. We should be able to handle if someone sends a suggestion with a different casing such as "en vinge", or if someone suggests something that is too similar such as "Gi noen en vinge". 

We should not verify wether exactly that expression exists but rather the degree of similarity with other expressions, and then indicate that in a column in the suggestions table. This will account for variations of the expression. 

Totally backing the ID sorting. Would be nice to be able to toggle ascending and descending as well.

**Comment by henrikmw** [comment]
Yeah I agree. Still think we can merge this for now as its better than having no check at all + we get id sorting @MarkusJohansen

**Comment by MarkusJohansen** [comment]
> Yeah I agree. Still think we can merge this for now as its better than having no check at all + we get id sorting @MarkusJohansen

Will do, but next time try to separate the PRs for different functionality😰

**Comment by henrikmw** [comment]
Ok nerd!!!

**Pull request merged**
